language: go

env:
  GO111MODULE=on

go:
  - 1.11.x
  - 1.12.x

git:
  depth: 1

install: true

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get github.com/gojp/goreportcard/cmd/goreportcard-cli

script:
  - golangci-lint run
  - go test -v -race ./...
  - go test -v -race ./auth-service/...
