// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginResponse_ErrorCode int32

const (
	LoginResponse_BAD_REQUEST                    LoginResponse_ErrorCode = 0
	LoginResponse_INTERNAL_ERROR                 LoginResponse_ErrorCode = 1
	LoginResponse_INCORRECT_USERNAME_OR_PASSWORD LoginResponse_ErrorCode = 2
	LoginResponse_BLANK_USERNAME                 LoginResponse_ErrorCode = 3
	LoginResponse_BLANK_PASSWORD                 LoginResponse_ErrorCode = 4
)

var LoginResponse_ErrorCode_name = map[int32]string{
	0: "BAD_REQUEST",
	1: "INTERNAL_ERROR",
	2: "INCORRECT_USERNAME_OR_PASSWORD",
	3: "BLANK_USERNAME",
	4: "BLANK_PASSWORD",
}

var LoginResponse_ErrorCode_value = map[string]int32{
	"BAD_REQUEST":                    0,
	"INTERNAL_ERROR":                 1,
	"INCORRECT_USERNAME_OR_PASSWORD": 2,
	"BLANK_USERNAME":                 3,
	"BLANK_PASSWORD":                 4,
}

func (x LoginResponse_ErrorCode) String() string {
	return proto.EnumName(LoginResponse_ErrorCode_name, int32(x))
}

func (LoginResponse_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_40c3308acdd691b6, []int{1, 0}
}

type CreateUserResponse_ErrorCode int32

const (
	CreateUserResponse_BAD_REQUEST      CreateUserResponse_ErrorCode = 0
	CreateUserResponse_INTERNAL_ERROR   CreateUserResponse_ErrorCode = 1
	CreateUserResponse_INVALID_EMAIL    CreateUserResponse_ErrorCode = 2
	CreateUserResponse_INVALID_USERNAME CreateUserResponse_ErrorCode = 3
	CreateUserResponse_USERNAME_TAKEN   CreateUserResponse_ErrorCode = 4
	CreateUserResponse_EMAIL_TAKEN      CreateUserResponse_ErrorCode = 5
	CreateUserResponse_BLANK_USERNAME   CreateUserResponse_ErrorCode = 6
	CreateUserResponse_BLANK_PASSWORD   CreateUserResponse_ErrorCode = 7
)

var CreateUserResponse_ErrorCode_name = map[int32]string{
	0: "BAD_REQUEST",
	1: "INTERNAL_ERROR",
	2: "INVALID_EMAIL",
	3: "INVALID_USERNAME",
	4: "USERNAME_TAKEN",
	5: "EMAIL_TAKEN",
	6: "BLANK_USERNAME",
	7: "BLANK_PASSWORD",
}

var CreateUserResponse_ErrorCode_value = map[string]int32{
	"BAD_REQUEST":      0,
	"INTERNAL_ERROR":   1,
	"INVALID_EMAIL":    2,
	"INVALID_USERNAME": 3,
	"USERNAME_TAKEN":   4,
	"EMAIL_TAKEN":      5,
	"BLANK_USERNAME":   6,
	"BLANK_PASSWORD":   7,
}

func (x CreateUserResponse_ErrorCode) String() string {
	return proto.EnumName(CreateUserResponse_ErrorCode_name, int32(x))
}

func (CreateUserResponse_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_40c3308acdd691b6, []int{3, 0}
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c3308acdd691b6, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Api                  string                  `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	OpaqueToken          string                  `protobuf:"bytes,2,opt,name=opaque_token,json=opaqueToken,proto3" json:"opaque_token,omitempty"`
	ErrorCode            LoginResponse_ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=auth.v1.LoginResponse_ErrorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c3308acdd691b6, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LoginResponse) GetOpaqueToken() string {
	if m != nil {
		return m.OpaqueToken
	}
	return ""
}

func (m *LoginResponse) GetErrorCode() LoginResponse_ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return LoginResponse_BAD_REQUEST
}

type CreateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c3308acdd691b6, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
	Api                  string                       `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Success              bool                         `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode            CreateUserResponse_ErrorCode `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,enum=auth.v1.CreateUserResponse_ErrorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c3308acdd691b6, []int{3}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateUserResponse) GetErrorCode() CreateUserResponse_ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return CreateUserResponse_BAD_REQUEST
}

func init() {
	proto.RegisterEnum("auth.v1.LoginResponse_ErrorCode", LoginResponse_ErrorCode_name, LoginResponse_ErrorCode_value)
	proto.RegisterEnum("auth.v1.CreateUserResponse_ErrorCode", CreateUserResponse_ErrorCode_name, CreateUserResponse_ErrorCode_value)
	proto.RegisterType((*LoginRequest)(nil), "auth.v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "auth.v1.LoginResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "auth.v1.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "auth.v1.CreateUserResponse")
}

func init() { proto.RegisterFile("auth-service.proto", fileDescriptor_40c3308acdd691b6) }

var fileDescriptor_40c3308acdd691b6 = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xbe, 0x76, 0xd2, 0xa6, 0x9d, 0xfe, 0x5c, 0x77, 0xda, 0x5b, 0xa5, 0xb9, 0x08, 0x19, 0x4b,
	0x48, 0x55, 0x44, 0xed, 0x26, 0x74, 0x15, 0x16, 0xe0, 0x26, 0x46, 0x8a, 0x9a, 0x26, 0x74, 0x92,
	0x80, 0xd4, 0x8d, 0xe5, 0x3a, 0x87, 0xc4, 0x90, 0xce, 0xb8, 0x33, 0xe3, 0x14, 0x21, 0x56, 0xf0,
	0x06, 0xb0, 0xe3, 0x01, 0xd8, 0xb2, 0xe2, 0x49, 0xd8, 0xb1, 0x44, 0x3c, 0x08, 0xb2, 0xe3, 0xa4,
	0x7f, 0xa1, 0x12, 0xab, 0xcc, 0xf9, 0xce, 0x37, 0xdf, 0xc9, 0x7c, 0xe7, 0xf8, 0x20, 0xec, 0x45,
	0x72, 0xb0, 0x23, 0x80, 0x8f, 0x02, 0x1f, 0xcc, 0x90, 0x33, 0xc9, 0x70, 0x2e, 0xc6, 0xcc, 0x51,
	0xa9, 0x70, 0xa7, 0xcf, 0x58, 0x7f, 0x08, 0x96, 0x17, 0x06, 0x96, 0x47, 0x29, 0x93, 0x9e, 0x0c,
	0x18, 0x15, 0x63, 0x5a, 0xe1, 0x41, 0xf2, 0xe3, 0xef, 0xf4, 0x81, 0xee, 0x88, 0x73, 0xaf, 0xdf,
	0x07, 0x6e, 0xb1, 0x30, 0x61, 0xdc, 0x64, 0x1b, 0x4f, 0xd1, 0x72, 0x83, 0xf5, 0x03, 0x4a, 0xe0,
	0x2c, 0x02, 0x21, 0x71, 0x01, 0x2d, 0x44, 0x02, 0x38, 0xf5, 0x4e, 0x21, 0xaf, 0xe8, 0xca, 0xf6,
	0x22, 0x99, 0xc6, 0x71, 0x2e, 0xf4, 0x84, 0x38, 0x67, 0xbc, 0x97, 0x57, 0xc7, 0xb9, 0x49, 0x6c,
	0x7c, 0x50, 0xd1, 0x4a, 0x2a, 0x24, 0x42, 0x46, 0x05, 0x60, 0x0d, 0x65, 0xbc, 0x30, 0x48, 0x45,
	0xe2, 0x23, 0xbe, 0x87, 0x96, 0x59, 0xe8, 0x9d, 0x45, 0xe0, 0x4a, 0xf6, 0x1a, 0x68, 0xaa, 0xb1,
	0x34, 0xc6, 0x3a, 0x31, 0x84, 0x1f, 0x23, 0x04, 0x9c, 0x33, 0xee, 0xfa, 0xac, 0x07, 0xf9, 0x8c,
	0xae, 0x6c, 0xaf, 0x96, 0x75, 0x33, 0x7d, 0xb8, 0x79, 0xa5, 0x80, 0xe9, 0xc4, 0xc4, 0x2a, 0xeb,
	0x01, 0x59, 0x84, 0xc9, 0xd1, 0x78, 0x87, 0x16, 0xa7, 0x38, 0xfe, 0x17, 0x2d, 0xed, 0xdb, 0x35,
	0x97, 0x38, 0x47, 0x5d, 0xa7, 0xdd, 0xd1, 0xfe, 0xc1, 0x18, 0xad, 0xd6, 0x9b, 0x1d, 0x87, 0x34,
	0xed, 0x86, 0xeb, 0x10, 0xd2, 0x22, 0x9a, 0x82, 0x0d, 0x74, 0xb7, 0xde, 0xac, 0xb6, 0x08, 0x71,
	0xaa, 0x1d, 0xb7, 0xdb, 0x8e, 0x93, 0x87, 0x8e, 0xdb, 0x22, 0xee, 0x33, 0xbb, 0xdd, 0x7e, 0xd1,
	0x22, 0x35, 0x4d, 0x8d, 0xef, 0xed, 0x37, 0xec, 0xe6, 0xc1, 0x34, 0xaf, 0x65, 0x2e, 0xb0, 0x29,
	0x2f, 0x6b, 0x78, 0x68, 0xad, 0xca, 0xc1, 0x93, 0xd0, 0x15, 0xc0, 0x27, 0x96, 0x6e, 0xa0, 0x39,
	0x38, 0xf5, 0x82, 0x61, 0x6a, 0xc5, 0x38, 0xb8, 0x62, 0xb4, 0x7a, 0x8b, 0xd1, 0x99, 0x6b, 0x46,
	0x7f, 0x55, 0x11, 0xbe, 0x5c, 0xe3, 0x8f, 0x6e, 0xe7, 0x51, 0x4e, 0x44, 0xbe, 0x0f, 0x42, 0x24,
	0xfa, 0x0b, 0x64, 0x12, 0xe2, 0xda, 0x0c, 0x93, 0xef, 0x4f, 0x4d, 0xbe, 0x29, 0x3e, 0xdb, 0xe9,
	0x2f, 0xca, 0x5f, 0x5b, 0xbd, 0x86, 0x56, 0xea, 0xcd, 0xe7, 0x76, 0xa3, 0x5e, 0x73, 0x9d, 0x43,
	0xbb, 0xde, 0xd0, 0x54, 0xbc, 0x81, 0xb4, 0x09, 0x74, 0xd5, 0xdb, 0x69, 0x27, 0x3a, 0xf6, 0x81,
	0xd3, 0xd4, 0xb2, 0x71, 0x85, 0xe4, 0x52, 0x0a, 0xcc, 0xcd, 0x68, 0xca, 0xfc, 0x8c, 0xa6, 0xe4,
	0xca, 0xdf, 0x14, 0x94, 0xb5, 0x23, 0x39, 0xc0, 0xc7, 0x08, 0x5d, 0x3c, 0x0e, 0x17, 0x66, 0xbe,
	0x38, 0x69, 0x59, 0xe1, 0xff, 0x5b, 0xdc, 0x30, 0xd6, 0xdf, 0x7f, 0xff, 0xf5, 0x49, 0x5d, 0x31,
	0x16, 0xac, 0x51, 0xc9, 0x8a, 0x79, 0x15, 0xa5, 0x88, 0x8f, 0xd0, 0x5c, 0x32, 0x9d, 0xf8, 0xbf,
	0xeb, 0xd3, 0x3a, 0x56, 0xdc, 0x9c, 0x3d, 0xc4, 0xc6, 0x56, 0x22, 0xb6, 0x6e, 0xac, 0x4e, 0xc4,
	0xac, 0x61, 0x9c, 0xaf, 0x28, 0xc5, 0xfd, 0x9f, 0xca, 0x47, 0xfb, 0x87, 0x82, 0x25, 0xda, 0x8c,
	0xff, 0x3d, 0x50, 0x19, 0xf8, 0xc9, 0xa7, 0xab, 0xa7, 0x6b, 0xc1, 0xe8, 0xa2, 0xe5, 0xcb, 0x6b,
	0x02, 0x17, 0x07, 0x52, 0x86, 0xa2, 0x62, 0x59, 0xfd, 0x40, 0x0e, 0xbd, 0x13, 0xd3, 0x67, 0xa7,
	0xd6, 0x5b, 0xe0, 0xcc, 0x7d, 0xc9, 0x99, 0x90, 0xd6, 0x65, 0x6e, 0x61, 0xeb, 0x22, 0xf1, 0x24,
	0xd9, 0x04, 0x34, 0x9e, 0xca, 0xf8, 0x4a, 0x39, 0x53, 0x32, 0x77, 0x8b, 0x8a, 0x52, 0xd6, 0xbc,
	0x30, 0x1c, 0xa6, 0x35, 0xad, 0x57, 0x82, 0xd1, 0xca, 0x0d, 0x84, 0x3c, 0x42, 0x99, 0xbd, 0xdd,
	0x3d, 0xbc, 0x87, 0x8a, 0x04, 0x64, 0xc4, 0x29, 0xf4, 0xf4, 0xf3, 0x01, 0x50, 0x5d, 0x0e, 0x40,
	0xe7, 0x20, 0x58, 0xc4, 0x7d, 0xd0, 0x7b, 0x0c, 0x84, 0x4e, 0x99, 0xd4, 0xe1, 0x4d, 0x20, 0xa4,
	0x89, 0xe7, 0x51, 0xf6, 0xb3, 0xaa, 0xe4, 0x8e, 0xd5, 0x51, 0xe9, 0x64, 0x3e, 0x29, 0xfe, 0xf0,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0xbe, 0x1a, 0x7d, 0xf1, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/auth.v1.Auth/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/auth.v1.Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedAuthServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.v1.Auth/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.v1.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Auth_CreateUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth-service.proto",
}
