// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/auth.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthResponse_Status int32

const (
	AuthResponse_APPROVED     AuthResponse_Status = 0
	AuthResponse_UNAUTHORIZED AuthResponse_Status = 1
	AuthResponse_ERROR        AuthResponse_Status = 2
)

var AuthResponse_Status_name = map[int32]string{
	0: "APPROVED",
	1: "UNAUTHORIZED",
	2: "ERROR",
}

var AuthResponse_Status_value = map[string]int32{
	"APPROVED":     0,
	"UNAUTHORIZED": 1,
	"ERROR":        2,
}

func (x AuthResponse_Status) String() string {
	return proto.EnumName(AuthResponse_Status_name, int32(x))
}

func (AuthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_15263a302b6905f5, []int{1, 0}
}

type AuthResponse_ErrorCode int32

const (
	AuthResponse_INTERNAL_SERVER AuthResponse_ErrorCode = 0
	AuthResponse_BAD_REQUEST     AuthResponse_ErrorCode = 1
	AuthResponse_PERMISSION      AuthResponse_ErrorCode = 2
)

var AuthResponse_ErrorCode_name = map[int32]string{
	0: "INTERNAL_SERVER",
	1: "BAD_REQUEST",
	2: "PERMISSION",
}

var AuthResponse_ErrorCode_value = map[string]int32{
	"INTERNAL_SERVER": 0,
	"BAD_REQUEST":     1,
	"PERMISSION":      2,
}

func (x AuthResponse_ErrorCode) String() string {
	return proto.EnumName(AuthResponse_ErrorCode_name, int32(x))
}

func (AuthResponse_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_15263a302b6905f5, []int{1, 1}
}

type AuthRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15263a302b6905f5, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthResponse struct {
	Status               AuthResponse_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=auth.v1.AuthResponse_Status" json:"status,omitempty"`
	ErrorCode            AuthResponse_ErrorCode `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=auth.v1.AuthResponse_ErrorCode" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_15263a302b6905f5, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetStatus() AuthResponse_Status {
	if m != nil {
		return m.Status
	}
	return AuthResponse_APPROVED
}

func (m *AuthResponse) GetErrorCode() AuthResponse_ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return AuthResponse_INTERNAL_SERVER
}

func init() {
	proto.RegisterEnum("auth.v1.AuthResponse_Status", AuthResponse_Status_name, AuthResponse_Status_value)
	proto.RegisterEnum("auth.v1.AuthResponse_ErrorCode", AuthResponse_ErrorCode_name, AuthResponse_ErrorCode_value)
	proto.RegisterType((*AuthRequest)(nil), "auth.v1.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "auth.v1.AuthResponse")
}

func init() { proto.RegisterFile("v1/auth.proto", fileDescriptor_15263a302b6905f5) }

var fileDescriptor_15263a302b6905f5 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4b, 0xf3, 0x40,
	0x14, 0xc4, 0x9b, 0xd0, 0xf6, 0xfb, 0xf2, 0x5a, 0xdb, 0x65, 0xad, 0x50, 0x44, 0x50, 0xe2, 0xc5,
	0x53, 0xa4, 0xad, 0x27, 0x0f, 0xc2, 0xa6, 0x59, 0x30, 0xa0, 0x49, 0x7c, 0x49, 0x7a, 0xe8, 0x25,
	0xd4, 0x76, 0x21, 0x50, 0xe8, 0xd6, 0x64, 0x93, 0xbf, 0xde, 0x83, 0x74, 0x53, 0x45, 0xa4, 0xb7,
	0x37, 0xf0, 0x9b, 0x61, 0xde, 0xc0, 0x59, 0x3d, 0xb9, 0x5f, 0x55, 0x2a, 0x77, 0xf6, 0x85, 0x54,
	0x92, 0xfe, 0xd3, 0x77, 0x3d, 0xb1, 0x6f, 0xa1, 0xc7, 0x2a, 0x95, 0xa3, 0xf8, 0xa8, 0x44, 0xa9,
	0xe8, 0x08, 0x3a, 0x89, 0xdc, 0x8a, 0xdd, 0xd8, 0xb8, 0x31, 0xee, 0x2c, 0x6c, 0x84, 0xfd, 0x69,
	0x40, 0xbf, 0xa1, 0xca, 0xbd, 0xdc, 0x95, 0x82, 0x3e, 0x40, 0xb7, 0x54, 0x2b, 0x55, 0x95, 0x9a,
	0x1b, 0x4c, 0xaf, 0x9c, 0x63, 0x9e, 0xf3, 0x1b, 0x73, 0x62, 0xcd, 0xe0, 0x91, 0xa5, 0x4f, 0x00,
	0xa2, 0x28, 0x64, 0x91, 0xad, 0xe5, 0x46, 0x8c, 0x4d, 0xed, 0xbc, 0x3e, 0xed, 0xe4, 0x07, 0x6e,
	0x2e, 0x37, 0x02, 0x2d, 0xf1, 0x7d, 0xda, 0x33, 0xe8, 0x36, 0x89, 0xb4, 0x0f, 0xff, 0x59, 0x14,
	0x61, 0xb8, 0xe0, 0x1e, 0x69, 0x51, 0x02, 0xfd, 0x34, 0x60, 0x69, 0xf2, 0x1c, 0xa2, 0xbf, 0xe4,
	0x1e, 0x31, 0xa8, 0x05, 0x1d, 0x8e, 0x18, 0x22, 0x31, 0x6d, 0x06, 0xd6, 0x4f, 0x18, 0x3d, 0x87,
	0xa1, 0x1f, 0x24, 0x1c, 0x03, 0xf6, 0x92, 0xc5, 0x1c, 0x17, 0x1c, 0x49, 0x8b, 0x0e, 0xa1, 0xe7,
	0x32, 0x2f, 0x43, 0xfe, 0x96, 0xf2, 0x38, 0x21, 0x06, 0x1d, 0x00, 0x44, 0x1c, 0x5f, 0xfd, 0x38,
	0xf6, 0xc3, 0x80, 0x98, 0x53, 0x17, 0xda, 0x87, 0x72, 0xf4, 0x11, 0xac, 0x79, 0x2e, 0xd6, 0x5b,
	0x2d, 0x46, 0x7f, 0x8a, 0xeb, 0xfd, 0x2e, 0x2f, 0x4e, 0xbe, 0x63, 0xb7, 0xdc, 0xf6, 0xd2, 0xac,
	0x27, 0xef, 0x5d, 0xbd, 0xfe, 0xec, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x3a, 0x92, 0x87, 0x8e,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	CheckAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) CheckAuth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/auth.v1.Auth/CheckAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	CheckAuth(context.Context, *AuthRequest) (*AuthResponse, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) CheckAuth(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAuth not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_CheckAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).CheckAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.v1.Auth/CheckAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).CheckAuth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAuth",
			Handler:    _Auth_CheckAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/auth.proto",
}
